api:
  base_url: "https://api.restajet.com/admin_v1"
  page_size: 5
  request_timeout: 30

database:
  server: "localhost\\SQLEXPRESS"
  database: "RestaOrders1"
  username: "sa"
  driver: "ODBC+Driver+17+for+SQL+Server"

logging:
  filename: "order_sync.log"
  level: "INFO"
  max_bytes: 10485760  # 10MB
  backup_count: 5

sync:
  polling_interval: 3  # 5 minutes
  request_delay: 1.0
  max_retries: 3
  delay_between_orders: 0.5
  delay_between_pages: 0.5
  delay_on_error: 5.0

schedule:
  # Run from 9:00 AM to 5:00 PM on weekdays
  start_hour: 11
  start_minute: 0
  end_hour: 17
  end_minute: 0
  active_days:
    - MONDAY
    - TUESDAY
    - WEDNESDAY
    - THURSDAY
    - FRIDAY
    - SATURDAY