api:
  base_url: "https://api.restajet.com/admin_v1"
  page_size: 5
  request_timeout: 30

database:
  server: "localhost\\SQLEXPRESS"
  database: "RestaOrders1"
  username: "sa"
  password: "qwerty"
  driver: "ODBC+Driver+17+for+SQL+Server"

logging:
  filename: "order_sync.log"
  level: "INFO"
  max_bytes: 10485760  # 10MB
  backup_count: 5

sync:
  polling_interval: 300  # 5 minutes
  request_delay: 1.0
  max_retries: 3
  delay_between_orders: 0.5
  delay_between_pages: 0.5
  delay_on_error: 5.0

restaurants:
  - name: "ProposUK"
    username: "msd79@outlook.com"
    password: "qwerty"